### ISSUE TITLE
Coloured text according to user colour

### ISSUE THREAD

**Issue by IgnacioLaner** [LewisTehMinerz/BootyfulDiscord#3]
Possibility to have the text a user writes the same color as the user's color.

**Comment by LewisTehMinerz** [comment]
there's a plugin for discordinjections that does that, i'm not sure if you can do it with css

**Comment by IgnacioLaner** [comment]
There is this functionality in BetterDiscord that you can enable and disable "Make text colour the same as role colour", I have it enabled and it doesn't work with your theme but it does with other themes.

**Comment by LewisTehMinerz** [comment]
i don't use betterdiscord, but if you or another person wants to make a fix, feel free.
